### ISSUE TITLE
Image with site name doesn't appear

### ISSUE THREAD

**Issue by Mini-chill** [audiomaster99/CS2BombsiteAnnouncer#2]
On each round start - Failed to load image data from https://i.imgur.com/WIC4VHx.png
And it's for both sites.

**Comment by itsAudioo** [comment]
> On each round start - Failed to load image data from https://i.imgur.com/WIC4VHx.png And it's for both sites.

` "bombsite-A-img": "https://raw.githubusercontent.com/audiomaster99/CS2BombsiteAnnouncer/main/.github/workflows/new-A.png",
  "bombsite-B-img": "https://raw.githubusercontent.com/audiomaster99/CS2BombsiteAnnouncer/main/.github/workflows/new-B.png",`
  replace images in config, imgur has some issues i guess
