### ISSUE TITLE
phrases error in build 16

### ISSUE THREAD

**Issue by freakexeuLow** [audiomaster99/CS2BombsiteAnnouncer#5]
hey, it looks like you miss something in the new build version :3

![translation error](https://github.com/audiomaster99/CS2BombsiteAnnouncer/assets/32603929/c574cd32-8085-4b4a-b0f5-ea30fadedd28)

**Comment by itsAudioo** [comment]
Use build before this one, cuz I didn't include lang folder in build.

**Comment by freakexeuLow** [comment]
> Use build before this one, cuz I didn't include lang folder in build.

Hey, I already know about the previous version, but wanted to report it before another server owner gets in touch and [https://github.com/audiomaster99/CS2BombsiteAnnouncer/issues/2](https://github.com/audiomaster99/CS2BombsiteAnnouncer/issues/2) you should also change the link img in your plugin with the next update and thanks for everything....keep it up 👍🏼

**Comment by itsAudioo** [comment]
> > Use build before this one, cuz I didn't include lang folder in build.
> 
> Hey, I already know about the previous version, but wanted to report it before another server owner gets in touch and #2 you should also change the link img in your plugin with the next update and thanks for everything....keep it up 👍🏼

everything u mentioned should be fixed in latest build
https://github.com/audiomaster99/CS2BombsiteAnnouncer/releases/tag/build-19
